apiVersion: v1
kind: Namespace
metadata:
  name: boundary
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.29
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.29
spec: {}
status: {}
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boundary-sa
  namespace: boundary
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: postgres
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: boundary
data:
  db-url: cG9zdGdyZXNxbDovL2JvdW5kYXJ5OmhlcmVXZWdvQWdhaW5AcG9zdGdyZXMucG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9ib3VuZGFyeT9zc2xtb2RlPWRpc2FibGUK
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
data:
  password: aGVyZVdlZ29BZ2Fpbg==
  root-password: SWFtVGhlTWFzdGVy
  username: Ym91bmRhcnk=
